import { Component } from '@angular/core';

@Component({
  selector: 'app-chat-rooms-section',
  templateUrl: './chat-rooms-section.component.html',
  styleUrls: ['./chat-rooms-section.component.css'],
})
export class ChatRoomsSectionComponent {
  users=[
    {
      id: 1,
      name: 'Alice Johnson',
      lastMessage: 'Hi there!',
      lastMessageTime: '10:30 AM',
      profilePhoto: 'https://placekitten.com/50/50',
    },
    {
      id: 2,
      name: 'Bob Smith',
      lastMessage: 'Hello!',
      lastMessageTime: '11:15 AM',
      profilePhoto: 'https://placekitten.com/51/50',
    },
    {
      id: 3,
      name: 'Charlie Brown',
      lastMessage: 'Hey!',
      lastMessageTime: '1:45 PM',
      profilePhoto: 'https://placekitten.com/52/50',
    },
    {
      id: 4,
      name: 'David Miller',
      lastMessage: "What's up?",
      lastMessageTime: '2:30 PM',
      profilePhoto: 'https://placekitten.com/53/50',
    },
    {
      id: 5,
      name: 'Emma Wilson',
      lastMessage: 'Good morning!',
      lastMessageTime: '8:00 AM',
      profilePhoto: 'https://placekitten.com/54/50',
    },
    {
      id: 6,
      name: 'Frank Brown MY Name Is Sunil Whats your NAme',
      lastMessage: 'Nice to meet you!',
      lastMessageTime: '3:20 PM',
      profilePhoto: 'https://placekitten.com/55/50',
    },
    {
      id: 7,
      name: 'Grace Taylor',
      lastMessage: 'How are you? sdlfjlas lasdflsj llsadjflsaj lsadjflsafj lasfdjlas lajsdfklasd',
      lastMessageTime: '5:45 PM',
      profilePhoto: 'https://placekitten.com/56/50',
    },
    {
      id: 8,
      name: 'Henry Davis',
      lastMessage: 'Have a great day!',
      lastMessageTime: '9:10 AM',
      profilePhoto: 'https://placekitten.com/57/50',
    },
    {
      id: 9,
      name: 'Isabel Moore',
      lastMessage: 'See you later!',
      lastMessageTime: '7:30 PM',
      profilePhoto: 'https://placekitten.com/58/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
    {
      id: 10,
      name: 'Jack Thomas',
      lastMessage: "How's it going?",
      lastMessageTime: '4:40 PM',
      profilePhoto: 'https://placekitten.com/59/50',
    },
  ];
}
